name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 -m pytest
        systemctl status gunicorn

    - name: Deploy to Linode
      if: ${{ success() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WINC_HOST }}
        username: ${{ secrets.WINC_USER_NAME }}
        key: ${{ secrets.GH_SECRET }}
        port: 22
        script: |
          cd /var/www/html/
          git pull origin main

