name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 -m pytest

    - name: Add Linode server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 172.233.46.163 >> ~/.ssh/known_hosts

    - name: Deploy to Linode
      if: ${{ success() }}
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key
        ssh-add /tmp/deploy_key
        ssh -o "StrictHostKeyChecking no" -A root@172.233.46.163 'cd /var/www/html/ && git pull origin main && systemctl restart gunicorn && systemctl restart nginx && gunicorn main:app --bind 0.0.0.0'
