name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
       
    - name: Run tests with pytest 
      run: |
        pytest tests 

  deploy: 
    runs-on: ubuntu-20.04
    needs: test
    steps:
    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WINC_HOST }}
        username: ${{ secrets.WINC_USER_NAME }}
        key: ${{ secrets.GH_SECRET }}
        port: 22
        script: |
          sh ./deploy.sh

